title: hexylena
author: Helena
email: hexylena@galaxians.rog
description: ""
baseurl: ""
url: "https://hexylena.galaxians.org/"
github_username: hexylena

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

include: [".well-known"]
