title: KTC-1400D
author: Dakota
email: webmaster@dakotaraine.xyz
description: ""
baseurl: ""
url: "https://comradedakota.github.io/KTC-1400D-Generator"
github_username: comradedakota

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

include: [".well-known"]
# exclude:
#   - _posts/*.roff
