title: ☕
author: Helena Rasche
email: hxr@hx42.org
description: ""
baseurl: ""
url: "https://erasche.github.io/"
github_username: erasche

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
