---
baseurl: https://erasche.github.io/
disablePathToLower: true
languageCode: en-us
title: 3bf57cec3c37
theme: "purehugo"
Paginate: 10
canonifyurls: true


params:
    twitterName: "Eric_Rasche"
    githubName: "erasche"
    picture: /assets/pics/me3.png
    description: "System Administrator"
