baseurl: https://erasche.github.io/
disablePathToLower: true
languageCode: en-us
title: Eric Rasche
theme: "purehugo"
Paginate: 10

params:
    twitterName: "Eric_Rasche"
    githubName: "erasche"
...
